version: '3'
services:
  eureka_server:
    build:
      context: ./eureka_server
    ports:
      - "8761:8761"

  mysqldb:
    image: mysql:latest
    container_name: mysqldb
    ports:
      - "3306:3306"
    restart: unless-stopped
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   environment:
  #     PMA_HOST: mysqldb
  #     PMA_PORT: 3306
  #     MYSQL_ROOT_PASSWORD: root
  #   ports:
  #     - "8081:80"

  demande-service:
    build:
      context: ./demande_service
    ports:
      - "8082:8082"
    depends_on:
      - eureka_server
      - mysqldb
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka_server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/demande_db?serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=

  offre-service:
    build:
      context: ./offre_service
    ports:
      - "8087:8087"
    depends_on:
      - mysqldb
      - eureka_server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka_server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/offer_db?serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=

  user_service:
    build:
      context: ./user_service
    ports:
      - "8088:8088"
    depends_on:
      - mysqldb
      - eureka_server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka_server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/user_db?serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect

