version: '3'
services:
  eureka_server:
    build:
      context: ./eureka_server
    ports:
      - "8761:8761"

  demande_service:
    build:
      context: ./demande_service
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka

  offre_service:
    build:
      context: ./offre_service
    ports:
      - "8087:8087"
    depends_on:
      - eureka-server
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka

  gateways:
    build:
      context: ./gateways
    ports:
      - "8888:8888"
    depends_on:
      - eureka-server
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka

  user_service:
    build:
      context: ./user_service
    ports:
      - "8088:8088"
    depends_on:
      - eureka-server
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka

