version: '3'
services:
  eureka_server:
    build:
      context: ./eureka_server
    restart: always
    ports:
      - "8761:8761"
    networks:
      - microservices-network
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - microservices-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    networks:
      - microservices-network

  demande-service:
    build:
      context: ./demande_service
    ports:
      - "8082:8082"
    depends_on:
      - mysql
      - eureka_server
    networks:
      - microservices-network
    environment:
      SPRING_CLOUD_EUREKA_HOST: eureka_server
      SPRING_CLOUD_EUREKA_PORT: 8761
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/demande_db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 2s
      retries: 100

  offre-service:
    build:
      context: ./offre_service
    ports:
      - "8087:8087"
    depends_on:
      - mysql
      - eureka_server
    networks:
      - microservices-network
    environment:
      SPRING_CLOUD_EUREKA_HOST: eureka_server
      SPRING_CLOUD_EUREKA_PORT: 8761
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/offer_db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 2s
      retries: 100

  user_service:
    build:
      context: ./user_service
    ports:
      - "8088:8088"
    depends_on:
      - mysql
      - eureka_server
    networks:
      - microservices-network
    environment:
      SPRING_CLOUD_EUREKA_HOST: eureka_server
      SPRING_CLOUD_EUREKA_PORT: 8761
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/user_db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 2s
      retries: 100

networks:
  microservices-network:
    driver: bridge